version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "chore:"
    assignees:
      - "frazzer951"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "chore:"
    assignees:
      - "frazzer951"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "chore:"
    assignees:
      - "frazzer951"
    groups:
      github-actions:
        patterns:
          - "*"
